### ISSUE TITLE
Mention that only the first line is updated in documentation

### ISSUE THREAD

**Issue by Akeboshiwind** [roddhjav/pass-update#18]
I was reading though the documentation and I found that it was only implicitly mentioned in the man page that only the first line of a password is updated. I had to read the code to confirm this was the case.

I believe that having the first line of the password file be the password is only a convention so it might not be implied that your plugin would work this way (at least I didn't assume it, but I'm new :D).

It might be worth adding to the README and man page to let people know this is what you're doing :)

**Comment by roddhjav** [comment]
I will merge it because it might be useful to some people. However, keep in mind that this is like the only requirement in the password-store "format". All the systems that support pass always assume it. In pass itself, `pass generate` and pass generate -i` use the first line as entry for the password.

**Comment by Akeboshiwind** [comment]
Thanks for merging, I think `pass generate` and the pass website are the only places where it's explicitly mentioned that this scheme is used, and even on the website it's only stated as a preference of the author.

Hopefully it being included in your documentation will make it a little less confusing for newcomers like me :)
